FROM python
WORKDIR /work
COPY ./requirements.txt /work
RUN pip3 install -r requirements.txt
RUN pip3 install torch==1.8.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
# RUN [ "python", "-c", "import nltk; nltk.download('all')" ]
