# Credits : https://www.panopy.com/iphone/secret-ada/cracking-a-cipher.html
APOSTOPHES = {
	"i'm" : "i am",
	"i'd" : "i would",
	"i've" : "i have",
	"he's" : "he is",
	"i'll" : "i will",
	"he'd" : "he would",
	"we'd" : "we would",
	"it'd" : "it would",
	"it's" : "it is",
	"can't" : "can not",
	"don't" : "do not",
	"we're" : "we are",
	"isn't" : "is not",
	"won't" : "would not",
	"we've" : "we have",
	"we'll" : "we will",
	"she's" : "she is",
	"you'd" : "you would",
	"let's" : "let us",
	"who's" : "who is",
	"he'll" : "he will",
	"it'll" : "it will",
	"she'd" : "she would",
	"ain't": "am not",
	"who'd" : "who would",
	"that's": "that is",
	"didn't": "did not",
	"you're" : "you are",
	"you'll" : "you will",
	"what's" : "what is",
	"wasn't" : "was not",
	"you've": "you have",
	"aren't" : "are not",
	"here's" : "here is",
	"hasn't" : "has not",
	"hadn't" : "had not",
	"they'd" : "they would",
	"here's" : "here is",
	"who've" : "who have",
	"she'll" : "she will",
	"who'll" : "who will",
	"that'd" : "that would",
	"doesn't" : "does not",
	"there's" : "there is",
	"they're" : "they are",
	"world's" : "world is",
	"haven't" : "have not",
	"they've" : "they have",
	"weren't" : "were not",
	"they'll" : "they will",
	"o'clock" : "of the clock",
	"mustn't" : "must not",
	"needn't" : "need not",
	"must've": "must have",
	"that'll" : "that will",
	"couldn't" : "could not",
	"wouldn't" : "would not",
	"could've" : "could have",
	"would've" : "would have",
	"there'll" : "there will",
	"shouldn't" : "should not",
	"should've" : "should have"
}